# @package _global_
defaults:
  - _self_

experiment: main2

### experiment args
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
log_path: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}, 'logs'}
data_overlay: ''
device: 'cuda'
config_mod: [] # Keep empty
ni: true
interact: false
feats_dir: 'datasets' # check 
stats_dir: 'datasets' # check 
seed: 1234 
verbose: 'info' # Verbose level: info | debug | warning | critical
stats_download: false
data_path: /vast/sd5313/data/BreakoutNoFrameskip-v4

resume_training: false
comment: ''

# OVERRIDES AND ARGS

# Model
no_ema: false

# Mode
mode: train # train, test, fast_fid, sample, video_gen
use_encoding: true
encoding_type: avg # avg, max
encoding_prob: 0.5
ckpt_path: null #/scratch/sd5313/CILVR/fall23/LLVM/mcvd/checkpoints/checkpoint_300K_bs128_3epsends.pt #/scratch/sd5313/CILVR/fall23/LLVM/mcvd/checkpoints/checkpoint_80k_bs32_0epends.pt # /scratch/sd5313/CILVR/fall23/LLVM/mcvd/checkpoints/checkpoint_80k_bs32_0epends.pt # '/scratch/mr6744/shared/checkpoint.pt'
episode_end: 3 # 3

# FID
fid_batch_size: 1000
no_pr: false
fid_num_samples: null
pr_nn_k: null

# Sampling
image_folder: 'images'
final_only: null

end_ckpt: null
freq: null

# Video
video_folder: 'videos'
subsample: null
ckpt: null
start_at: 0

###### End of args ######

training:
  L1: false
  batch_size: 32
  n_epochs: 1000000
  n_iters: 3000001
  snapshot_freq: 1500
  snapshot_sampling: false
  sample_freq: 50000
  val_freq: 1000
  log_freq: 100
  log_all_sigmas: false

sampling:
  batch_size: 100
  data_init: false
  ckpt_id: null
  final_only: true
  fid: false
  ssim: true
  fvd: true
  denoise: true
  subsample: 100
  num_samples4fid: 10000
  num_samples4fvd: 10000
  inpainting: false
  interpolation: false # Set to true for interpolation (doesnt work currently), otherwise conditional/unconditional generation based on data.num_frames_cond
  n_interpolations: 15
  consistent: true
  step_lr: 0.0
  n_steps_each: 0
  train: false
  num_frames_pred: 28
  clip_before: true
  max_data_iter: 10
  init_prev_t: -1.0 # if >0, we start next_frame at prev_frame starting with noise t=init_prev_t
  one_frame_at_a_time: false # ALWAYS FALSE
  preds_per_test: 5

fast_fid:
  batch_size: 1000
  num_samples: 1000
  begin_ckpt: 5000
  freq: 5000
  end_ckpt: 300000
  pr_nn_k: 3
  verbose: false
  ensemble: false
  step_lr: 0.0
  n_steps_each: 0

test:
  begin_ckpt: 5000
  end_ckpt: 300000
  batch_size: 100

data:
  dataset: "BreakoutNoFrameskip-v4"
  image_size: 64
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: true
  color_jitter: 0.2
  num_workers: 0
  num_frames: 5
  num_frames_cond: 2
  num_frames_future: 2
  prob_mask_cond: 0.5
  prob_mask_future: 0.5
  prob_mask_sync: false # If true, then prediction never happens, only generation and interpolation

model:
  depth: deeper
  version: DDPM
  gamma: false
  arch: unetmore # DONT CHANGE
  type: v1
  time_conditional: true
  dropout: 0.1
  sigma_dist: linear
  sigma_begin: 0.02
  sigma_end: 0.0001
  num_classes: 1000
  ema: true
  ema_rate: 0.999
  spec_norm: false
  normalization: InstanceNorm++
  nonlinearity: swish
  ngf: 32
  ch_mult: 
    - 1
    - 2
    - 2
    - 2
  num_res_blocks: 3 # 8 for traditional
  attn_resolutions: 
    - 8
    - 16
    - 32 # can use only 16 for traditional
  n_head_channels: 64 # -1 for traditional
  conditional: true
  noise_in_cond: false
  output_all_frames: false # ALWAYS SET TO FALSE. could be useful especially for 3d models
  cond_emb: false
  spade: false
  spade2: true # To use this, set to true and set spade to false
  spade_dim: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  warmup: 5000
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0